name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/ci-reusable.yml

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://npm.pkg.github.com/
          cache: "yarn"

#      TODO: get version number in the build automatically
#      without using package.json version
#      - name: Extract version from tag
#        id: extract_version
#        run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\/v/}"
#
#      - name: Install jq
#        run: sudo apt-get install jq
#
#      - name: Update package version
#        run: |
#          jq '.version = steps.extract_version.output' package.json > package.tmp.json
#          mv package.tmp.json package.json

      - name: Install dependencies
        run: yarn install --immutable

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
